version: '3.9'

services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  #Node API services
  api:
    container_name: api_container
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ../sniffer/
        target: /usr/src/app
    command: npm run dev
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
